; =====================================================================
; FermCon - configuration PlatformIO
; env:esp32-c6  -> build & flash sur la cible reelle (ESP32-C6)
; =====================================================================

[env:esp32-c6]
board = esp32-c6-devkitc-1
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.39/platform-espressif32.zip
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Flash 8 Mo + table de partitions double OTA (~3,19 Mo/app + 1,5 Mo FS)
board_upload.flash_size = 8MB
board_build.flash_size = 8MB
board_build.partitions = default_8MB.csv

lib_deps =
    lovyan03/LovyanGFX@^1.2.7
    bblanchon/ArduinoJson@^7.2.0
    ayushsharma82/ElegantOTA
    tzapu/WiFiManager
    ESP32Async/ESPAsyncWebServer
    ESP32Async/AsyncTCP
    knolleary/PubSubClient
    milesburton/DallasTemperature
    pstolarz/OneWireNg          ; remplace paulstoffregen/OneWire (incompatible ESP32-C6)

lib_ignore =
    OneWire                     ; ignore le OneWire de PaulStoffregen ; OneWireNg fournit son OneWire.h compatible C6

build_flags =
    -D ELEGANTOTA_USE_ASYNC_WEBSERVER=1   ; ElegantOTA en mode AsyncWebServer (evite l'ambiguite HTTP_GET/HTTP_POST)

; Options offsets ST7789 possibles pour ecran 2.25 pouces :
; -DCGRAM_OFFSET=0x0
; -DCGRAM_OFFSET=0x20
; -DCGRAM_OFFSET=0x40
